version: '3.8'

services:
  base-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  base-kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
